name: Deploy to Namecheap Web Hosting 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - uses: actions/setup-node@v2
      with: 
        node-version: 16
        
    - uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        protocol: sftp
        server: premium105.web-hosting.com
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        port: 21098 
        local-dir: ./
        server-dir: /public_html/
